/*
 * DC_MOTOR_program.c
 *
 * Created: 3/17/2024 8:57:36 AM
 *  Author: Go
 */ 

#define F_CPU 16000000UL

#include <util/delay.h>

#include "../../UTIL/STD_TYPES.h"
#include "../../UTIL/BIT_MATH.h"

#include "../../MCAL/DIO/DIO_interface.h"
#include "../../MCAL/DIO/DIO_private.h"

#include "../../MCAL/TIMER/TIMER_2/TMR2_config.h"
#include "../../MCAL/TIMER/TIMER_2/TMR2_interface.h"
#include "../../MCAL/TIMER/TIMER_2/TMR2_private.h"

#include "../../HAL/DC_MOTOR/DC_MOTOR_interface.h"
#include "../../HAL/DC_MOTOR/DC_MOTOR_config.h"

void MOTORS_Init()
{
	//Directions for both motors
	DIO_setPinDirection(MOTOR_LEFTPORT,MOTOR_LEFTINPUT1,DIO_PIN_OUTPUT);
	DIO_setPinDirection(MOTOR_LEFTPORT,MOTOR_LEFTINPUT2,DIO_PIN_OUTPUT);
	DIO_setPinDirection(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT1,DIO_PIN_OUTPUT);
	DIO_setPinDirection(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT2,DIO_PIN_OUTPUT);
	
	// Enable Settings for both motors
	
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT2,DIO_PIN_LOW);
	
	
	// Motor2 Control
	
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT2,DIO_PIN_LOW);
	
	
}

void CAR_MoveForward ()
{
	
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT2,DIO_PIN_HIGH);
	
	
	// Motor2 Control
	
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT2,DIO_PIN_HIGH);
	
}

void CAR_MoveBackward ()
{
	//DIO_setPinValue(MOTOR_ENABLEPORT,MOTOR_ENABLEPIN,DIO_PIN_HIGH);
	
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT1,DIO_PIN_HIGH);
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT2,DIO_PIN_LOW);
	
	// Motor2 Control
	
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT1,DIO_PIN_HIGH);
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT2,DIO_PIN_LOW);
}


void CAR_Stop ()
{
	//DIO_setPinValue(MOTOR_ENABLEPORT,MOTOR_ENABLEPIN,DIO_PIN_HIGH);
	
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT2,DIO_PIN_LOW);
	
	
	// Motor2 Control
	
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT2,DIO_PIN_LOW);
}


void CAR_MoveForwardRight ()
{
	//DIO_setPinValue(MOTOR_ENABLEPORT,MOTOR_ENABLEPIN,DIO_PIN_HIGH);
	//RIGHT WHEELS STOP, LEFT WHEELS FORWARD
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT2,DIO_PIN_HIGH);
	
	
	// Motor2 Control
	
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT2,DIO_PIN_LOW);
	
}

void CAR_MoveForwardleft ()
{
	//DIO_setPinValue(MOTOR_ENABLEPORT,MOTOR_ENABLEPIN,DIO_PIN_HIGH);
	//LEFT WHEELS STOP, RIGHT WHEELS FORWARD
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT2,DIO_PIN_LOW);
	
	
	// Motor2 Control
	
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT2,DIO_PIN_HIGH);
}

void CAR_MoveBackwardleft ()
{
	//DIO_setPinValue(MOTOR_ENABLEPORT,MOTOR_ENABLEPIN,DIO_PIN_HIGH);
	
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT2,DIO_PIN_LOW);
	
	
	// Motor2 Control
	
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT1,DIO_PIN_HIGH);
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT2,DIO_PIN_LOW);
}

void CAR_MoveBackwardRight ()
{
	//DIO_setPinValue(MOTOR_ENABLEPORT,MOTOR_ENABLEPIN,DIO_PIN_HIGH);
	
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT1,DIO_PIN_HIGH);
	DIO_setPinValue(MOTOR_LEFTPORT,MOTOR_LEFTINPUT2,DIO_PIN_LOW);
	
	
	// Motor2 Control
	
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT1,DIO_PIN_LOW);
	DIO_setPinValue(MOTOR_RIGHTPORT,MOTOR_RIGHTINPUT2,DIO_PIN_LOW);
}


void CAR_SendDutyCycleAndStart(u8 speed)
{
	MOTORS_Init();
	TMR2_init();
	TMR2_SetDutyCycleValue_FastPWM(speed); // RANGE FROM 0 to 100
	TMR2_Start();
}